SET search_path TO goodfood;
CREATE TYPE "UserRole" AS ENUM ('USER', 'MANAGER', 'ADMIN');
CREATE TYPE "SourcingPlatform" AS ENUM ('BAND', 'ALIEXPRESS');
CREATE TYPE "ChannelKind" AS ENUM ('WHOLESALE', 'RETAIL');
CREATE TYPE "PriceTier" AS ENUM ('WHOLESALE', 'RETAIL');
CREATE TYPE "ChannelPlatform" AS ENUM ('BAND', 'NAVER_CAFE', 'ALIEXPRESS', 'SMARTSTORE', 'COUPANG', 'CUSTOM', 'CAFE24', 'OWNERCLAN', 'SHOPIFY', 'CUSTOM_API');
CREATE TYPE "AiProvider" AS ENUM ('GEMINI', 'OPENAI', 'CLAUDE');
CREATE TYPE "WorkflowType" AS ENUM ('COLLECT', 'TRANSFORM', 'PUBLISH', 'FULL_PIPELINE');
CREATE TYPE "WorkflowStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'PARTIAL_SUCCESS', 'WAITING_SESSION');
CREATE TYPE "TriggerType" AS ENUM ('MANUAL', 'SCHEDULED');
CREATE TYPE "StepType" AS ENUM ('COLLECTION', 'TRANSFORM', 'PRODUCT_CREATE', 'PUBLISH');
CREATE TYPE "StepStatus" AS ENUM ('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'SKIPPED');
CREATE TYPE "CustomerOrderStatus" AS ENUM ('PENDING', 'PAID', 'PREPARING', 'SHIPPED', 'DELIVERED', 'CANCELLED', 'REFUNDED');
CREATE TYPE "TossPaymentMethod" AS ENUM ('CARD', 'VIRTUAL_ACCOUNT', 'TRANSFER', 'MOBILE', 'CULTURE_GIFT', 'BOOK_GIFT', 'GAME_GIFT', 'BANK_TRANSFER');
CREATE TYPE "TossPaymentStatus" AS ENUM ('READY', 'IN_PROGRESS', 'WAITING_FOR_DEPOSIT', 'DONE', 'CANCELED', 'PARTIAL_CANCELED', 'ABORTED', 'EXPIRED');
CREATE TYPE "DiscountType" AS ENUM ('PERCENTAGE', 'FIXED_AMOUNT', 'FIXED', 'FREE_SHIPPING');
CREATE TYPE "InquiryType" AS ENUM ('PRODUCT', 'DELIVERY', 'ORDER', 'PAYMENT', 'RETURN', 'EXCHANGE', 'GENERAL');
CREATE TYPE "InquiryStatus" AS ENUM ('PENDING', 'ANSWERED');
CREATE TYPE "ReturnType" AS ENUM ('CANCEL', 'RETURN', 'EXCHANGE');
CREATE TYPE "ReturnStatus" AS ENUM ('REQUESTED', 'REVIEWING', 'APPROVED', 'REJECTED', 'PROCESSING', 'COMPLETED');
CREATE TYPE "RefundMethod" AS ENUM ('CREDIT_CARD', 'BANK_TRANSFER', 'POINTS');
CREATE TYPE "NotificationType" AS ENUM ('ORDER', 'CANCEL', 'REFUND', 'INQUIRY', 'SETTLEMENT', 'COLLECT', 'TRANSFORM', 'PUBLISH', 'ERROR', 'INFO');
CREATE TYPE "WholesaleOrderStatus" AS ENUM ('PENDING', 'ORDERED', 'CONFIRMED');
CREATE TYPE "BundleShippingType" AS ENUM ('NONE', 'INCLUDED', 'SEPARATE');
CREATE TYPE "PostType" AS ENUM ('SELF', 'OUTSOURCE', 'SHARED');
CREATE TYPE "OrderSource" AS ENUM ('SHOP', 'CHAT', 'KAKAO', 'MANUAL');
CREATE TYPE "ExternalOrderKind" AS ENUM ('RETAIL', 'WHOLESALE');
CREATE TYPE "SourceStatus" AS ENUM ('ACTIVE', 'SOLDOUT', 'POST_DELETED', 'PRICE_CHANGED');
CREATE TYPE "B2bStatus" AS ENUM ('NONE', 'PENDING', 'APPROVED', 'REJECTED');
CREATE TYPE "AgentLayer" AS ENUM ('COMMAND', 'SOURCING', 'OPERATIONS', 'COMMERCE', 'INFRA');
CREATE TYPE "AgentStatus" AS ENUM ('ACTIVE', 'INACTIVE', 'ERROR', 'MAINTENANCE');
CREATE TYPE "TaskStatus" AS ENUM ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED');
CREATE TYPE "TaskPriority" AS ENUM ('CRITICAL', 'HIGH', 'NORMAL', 'LOW');
CREATE TYPE "LogLevel" AS ENUM ('DEBUG', 'INFO', 'WARN', 'ERROR', 'CRITICAL');
CREATE TYPE "BankApiProvider" AS ENUM ('NONE', 'TOSS', 'KAKAOBANK', 'KFTC', 'CUSTOM');
CREATE TYPE "MessageChannel" AS ENUM ('BAND_COMMENT', 'BAND_CHAT', 'KAKAO', 'SMS');
CREATE TYPE "MessageDirection" AS ENUM ('INBOUND', 'OUTBOUND');
CREATE TYPE "KakaoSendStatus" AS ENUM ('DRAFT', 'PREVIEW', 'SENT', 'FAILED');
CREATE TYPE "SettlementStatus" AS ENUM ('PENDING', 'COMPLETED', 'CANCELLED');
CREATE TYPE "SubscriptionStatus" AS ENUM ('ACTIVE', 'PAST_DUE', 'CANCELLED', 'EXPIRED', 'TRIALING');
CREATE TABLE "user_address" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "label" varchar(50),
  "recipient_name" varchar(100) NOT NULL,
  "recipient_phone" varchar(20) NOT NULL,
  "postal_code" varchar(10) NOT NULL,
  "address" varchar(500) NOT NULL,
  "address_detail" varchar(500),
  "is_default" boolean NOT NULL DEFAULT false,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "agent_definitions" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "displayName" text NOT NULL,
  "layer" "AgentLayer" NOT NULL,
  "icon" text NOT NULL,
  "description" text NOT NULL,
  "status" "AgentStatus" NOT NULL DEFAULT 'INACTIVE'::"AgentStatus",
  "config" jsonb NOT NULL,
  "priority" integer NOT NULL DEFAULT 5,
  "maxConcurrent" integer NOT NULL DEFAULT 5,
  "retryPolicy" jsonb NOT NULL,
  "schedule" text,
  "aiModel" text,
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL,
  "deletedAt" timestamp(3),
  PRIMARY KEY ("id")
);
CREATE TABLE "agent_tasks" (
  "id" text NOT NULL,
  "agentId" text NOT NULL,
  "user_id" integer,
  "eventType" text NOT NULL,
  "payload" jsonb NOT NULL,
  "status" "TaskStatus" NOT NULL DEFAULT 'QUEUED'::"TaskStatus",
  "priority" "TaskPriority" NOT NULL DEFAULT 'NORMAL'::"TaskPriority",
  "result" jsonb,
  "error" text,
  "startedAt" timestamp(3),
  "completedAt" timestamp(3),
  "duration" integer,
  "retryCount" integer NOT NULL DEFAULT 0,
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "agent_logs" (
  "id" text NOT NULL,
  "agentId" text NOT NULL,
  "user_id" integer,
  "level" "LogLevel" NOT NULL DEFAULT 'INFO'::"LogLevel",
  "message" text NOT NULL,
  "metadata" jsonb,
  "taskId" text,
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "agent_kpi_records" (
  "id" text NOT NULL,
  "agentId" text NOT NULL,
  "metric" text NOT NULL,
  "value" double precision NOT NULL,
  "target" double precision NOT NULL,
  "period" text NOT NULL,
  "date" timestamp(3) NOT NULL,
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "agent_workflows" (
  "id" text NOT NULL,
  "name" text NOT NULL,
  "triggerEvent" text NOT NULL,
  "isActive" boolean NOT NULL DEFAULT true,
  "config" jsonb NOT NULL,
  "executionCount" integer NOT NULL DEFAULT 0,
  "lastExecuted" timestamp(3),
  "createdAt" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" timestamp(3) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "agent_workflow_steps" (
  "id" text NOT NULL,
  "workflowId" text NOT NULL,
  "agentId" text NOT NULL,
  "order" integer NOT NULL,
  "isParallel" boolean NOT NULL DEFAULT false,
  "config" jsonb,
  PRIMARY KEY ("id")
);
CREATE TABLE "sourcing_conditions" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "categories" jsonb NOT NULL,
  "min_price" integer,
  "max_price" integer,
  "min_margin_rate" double precision,
  "include_keywords" jsonb,
  "exclude_keywords" jsonb,
  "channel_ids" jsonb,
  "priority_sourcing" boolean NOT NULL DEFAULT false,
  "max_daily_count" integer,
  "schedule" varchar(50),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "api_client" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "client_id" varchar(40) NOT NULL,
  "client_secret" varchar(128) NOT NULL,
  "scopes" varchar(255) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "rate_limit" integer NOT NULL DEFAULT 60,
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "api_token" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "client_id" integer NOT NULL,
  "access_token" varchar(64) NOT NULL,
  "expires_at" timestamp(3) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "api_call_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "client_id" integer NOT NULL,
  "method" varchar(10) NOT NULL,
  "path" varchar(255) NOT NULL,
  "status_code" integer NOT NULL,
  "duration_ms" integer NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "pricing_policy" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "channel_id" integer NOT NULL,
  "name" varchar(100) NOT NULL,
  "description" text,
  "content" text NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "tier_rules" jsonb,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "pricing_policy_target" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "pricing_policy_id" integer NOT NULL,
  "retail_channel_id" integer NOT NULL,
  "apply_mode" varchar(20) NOT NULL DEFAULT 'INHERIT',
  "custom_content" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "automation_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "is_enabled" boolean NOT NULL DEFAULT false,
  "cron_expression" varchar(500),
  "ai_provider" "AiProvider" NOT NULL DEFAULT 'GEMINI'::"AiProvider",
  "last_run_at" timestamp(0),
  "next_run_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "channel_ids" text,
  "retail_channel_ids" text,
  "shop_ids" text,
  "pipeline_steps" text,
  "collection_limit" integer NOT NULL DEFAULT 10,
  "collection_limit_by_channel" text,
  "auto_publish_limit" integer NOT NULL DEFAULT 20,
  "auto_publish_limit_by_shop" text,
  "auto_publish_limit_by_channel" text,
  "digest_mode" varchar(20) NOT NULL DEFAULT 'individual',
  "digest_products_per_post" integer NOT NULL DEFAULT 20,
  "digest_images_per_product" integer NOT NULL DEFAULT 1,
  "band_publish_method" varchar(20) NOT NULL DEFAULT 'COMPOSE',
  "publish_target" varchar(20) NOT NULL DEFAULT 'BOTH',
  "price_change_policy" varchar(20) NOT NULL DEFAULT 'NOTIFY_ONLY',
  PRIMARY KEY ("id")
);
CREATE TABLE "workflow_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "workflow_type" "WorkflowType" NOT NULL,
  "trigger_type" "TriggerType" NOT NULL DEFAULT 'MANUAL'::"TriggerType",
  "status" "WorkflowStatus" NOT NULL DEFAULT 'PENDING'::"WorkflowStatus",
  "current_step" "StepType",
  "started_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "completed_at" timestamp(0),
  "total_items" integer NOT NULL DEFAULT 0,
  "success_count" integer NOT NULL DEFAULT 0,
  "failed_count" integer NOT NULL DEFAULT 0,
  "error_message" text,
  PRIMARY KEY ("id")
);
CREATE TABLE "workflow_step_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "workflow_id" integer NOT NULL,
  "step_type" "StepType" NOT NULL,
  "step_order" integer NOT NULL,
  "status" "StepStatus" NOT NULL DEFAULT 'PENDING'::"StepStatus",
  "started_at" timestamp(0),
  "completed_at" timestamp(0),
  "total_items" integer NOT NULL DEFAULT 0,
  "processed_items" integer NOT NULL DEFAULT 0,
  "success_count" integer NOT NULL DEFAULT 0,
  "failed_count" integer NOT NULL DEFAULT 0,
  "details" text,
  "error_message" text,
  "deleted_at" timestamp(0),
  PRIMARY KEY ("id")
);
CREATE TABLE "band_notice_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "is_enabled" boolean NOT NULL DEFAULT false,
  "schedule_times" text NOT NULL DEFAULT '["11:00","13:00","17:00"]',
  "top_n" integer NOT NULL DEFAULT 5,
  "pin_as_important" boolean NOT NULL DEFAULT true,
  "retail_channel_ids" text NOT NULL DEFAULT '[]',
  "source_channel_ids" text NOT NULL DEFAULT '[]',
  "category_codes" text NOT NULL DEFAULT '[]',
  "tone_hint" text,
  "last_run_at" timestamp(0),
  "last_run_message" text,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "bank_account" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "bank_name" varchar(50) NOT NULL,
  "account_number" varchar(50) NOT NULL,
  "account_holder" varchar(100) NOT NULL,
  "api_provider" "BankApiProvider" NOT NULL DEFAULT 'NONE'::"BankApiProvider",
  "api_credentials" jsonb,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_synced_at" timestamp(0),
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "bank_transaction" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "bank_account_id" integer NOT NULL,
  "transaction_date" timestamp(0) NOT NULL,
  "amount" decimal(12,2) NOT NULL,
  "sender_name" varchar(100),
  "description" varchar(500),
  "matched_order_id" integer,
  "matched_at" timestamp(0),
  "raw" jsonb,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "cart" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "session_id" varchar(100) NOT NULL,
  "user_id" integer,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "expires_at" timestamp(0) NOT NULL,
  "shop_id" integer,
  PRIMARY KEY ("id")
);
CREATE TABLE "cart_item" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "cart_id" integer NOT NULL,
  "shop_product_id" integer NOT NULL,
  "variant_id" integer,
  "quantity" integer NOT NULL DEFAULT 1,
  "price_at" integer NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "category" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "code" varchar(100) NOT NULL,
  "name" varchar(100) NOT NULL,
  "parent_id" integer,
  "depth" integer NOT NULL DEFAULT 1,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "channel_product" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "product_id" integer,
  "channel_id" integer NOT NULL,
  "post_key" varchar(255),
  "is_active" boolean NOT NULL DEFAULT true,
  "published_at" timestamp(0),
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "legacy_published_product_id" integer,
  "price_tier" "PriceTier",
  "publish_batch_id" varchar(64),
  "price_snapshot" jsonb,
  PRIMARY KEY ("id")
);
CREATE TABLE "channel" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "kind" "ChannelKind" NOT NULL,
  "platform" "ChannelPlatform" NOT NULL,
  "channel_key" varchar(255) NOT NULL,
  "name" varchar(255) NOT NULL,
  "cover_url" varchar(500),
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "shop_id" integer,
  "band_session_cookie" text,
  "session_expires_at" timestamp(3),
  "session_account_email" varchar(255),
  "order_deadline" varchar(50),
  "min_sourcing_price" integer,
  "max_sourcing_price" integer,
  "post_type" "PostType",
  "footer_image_url" varchar(1000),
  "publish_price_tier" "PriceTier" NOT NULL DEFAULT 'RETAIL'::"PriceTier",
  "band_publish_method" varchar(20) NOT NULL DEFAULT 'COMPOSE',
  "band_no" integer,
  "expiry_days_normal" integer,
  "expiry_days_com" integer,
  "auto_expire_enabled" boolean NOT NULL DEFAULT true,
  "catalog_id" integer,
  PRIMARY KEY ("id")
);
CREATE TABLE "collected_product" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "collected_post_id" integer NOT NULL,
  "name" varchar(500),
  "description" text,
  "currency" varchar(10) NOT NULL DEFAULT 'KRW',
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "raw_metadata" text,
  "is_converted" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE TABLE "coupon" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "code" varchar(50) NOT NULL,
  "name" varchar(200) NOT NULL,
  "description" text,
  "discount_type" "DiscountType" NOT NULL,
  "discount_value" decimal(10,2) NOT NULL,
  "min_purchase_amount" decimal(10,2),
  "max_discount_amount" decimal(10,2),
  "issued_count" integer NOT NULL DEFAULT 0,
  "max_issue_count" integer,
  "valid_from" timestamp(0) NOT NULL,
  "valid_until" timestamp(0) NOT NULL,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "user_coupon" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "coupon_id" integer NOT NULL,
  "is_used" boolean NOT NULL DEFAULT false,
  "used_at" timestamp(0),
  "order_id" integer,
  "issued_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "expired_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "external_mall_connection" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "platform" varchar(20) NOT NULL,
  "purpose" varchar(20) NOT NULL,
  "api_base_url" varchar(500),
  "api_key" varchar(500),
  "api_secret" varchar(500),
  "access_token" text,
  "refresh_token" text,
  "token_expires_at" timestamp(0),
  "mall_id" varchar(100),
  "shop_url" varchar(500),
  "sourcing_config" jsonb,
  "checkout_config" jsonb,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_sync_at" timestamp(0),
  "last_error" text,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "deleted_at" timestamp(0),
  PRIMARY KEY ("id")
);
CREATE TABLE "external_sourced_product" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "connection_id" integer NOT NULL,
  "external_product_id" varchar(100) NOT NULL,
  "external_url" varchar(1000) NOT NULL,
  "external_data" jsonb,
  "product_id" integer,
  "checkout_connection_id" integer,
  "checkout_product_id" varchar(100),
  "checkout_url" varchar(1000),
  "last_sync_at" timestamp(0),
  "price_at_source" integer,
  "price_at_checkout" integer,
  "stock_status" varchar(20),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "external_order" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "checkout_connection_id" integer NOT NULL,
  "external_order_id" varchar(100),
  "sourced_product_id" integer NOT NULL,
  "product_name" varchar(500) NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "order_amount" integer,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "customer_name" varchar(100),
  "customer_phone" varchar(20),
  "shipping_address" varchar(500),
  "tracking_code" varchar(100),
  "clicked_at" timestamp(0),
  "ordered_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "guest_order" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "shop_id" integer,
  "order_number" varchar(50) NOT NULL,
  "status" "CustomerOrderStatus" NOT NULL DEFAULT 'PENDING'::"CustomerOrderStatus",
  "guest_name" varchar(100) NOT NULL,
  "guest_phone" varchar(20) NOT NULL,
  "guest_email" varchar(200),
  "subtotal_amount" decimal(12,2) NOT NULL,
  "discount_amount" decimal(10,2) NOT NULL DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL,
  "ordered_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "paid_at" timestamp(0),
  "preparing_at" timestamp(0),
  "shipped_at" timestamp(0),
  "delivered_at" timestamp(0),
  "cancelled_at" timestamp(0),
  "cancel_reason" varchar(500),
  "cancelled_by" varchar(20),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "wholesale_order_status" "WholesaleOrderStatus",
  "wholesale_channel_id" integer,
  "wholesale_ordered_at" timestamp(0),
  "source" "OrderSource" NOT NULL DEFAULT 'SHOP'::"OrderSource",
  "external_kind" "ExternalOrderKind",
  "external_memo" text,
  "admin_memo" text,
  "admin_memo_updated_at" timestamp(0),
  "inbox_message_id" integer,
  PRIMARY KEY ("id")
);
CREATE TABLE "guest_order_item" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guest_order_id" integer NOT NULL,
  "shop_product_id" integer,
  "variant_id" integer,
  "product_name" varchar(500) NOT NULL,
  "option_summary" varchar(500),
  "thumbnail_url" varchar(1000),
  "is_custom_item" boolean NOT NULL DEFAULT false,
  "quantity" integer NOT NULL,
  "unit_price" decimal(12,2) NOT NULL,
  "total_price" decimal(12,2) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "guest_payment" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guest_order_id" integer NOT NULL,
  "payment_key" varchar(200),
  "toss_order_id" varchar(100),
  "method" "TossPaymentMethod" NOT NULL,
  "status" "TossPaymentStatus" NOT NULL DEFAULT 'READY'::"TossPaymentStatus",
  "amount" decimal(12,2) NOT NULL,
  "virtual_account_number" varchar(50),
  "virtual_account_bank" varchar(20),
  "virtual_account_due_date" timestamp(0),
  "card_company" varchar(50),
  "card_number" varchar(20),
  "installment_month" integer,
  "cancel_reason" varchar(500),
  "cancelled_amount" decimal(12,2),
  "raw_response" text,
  "approved_at" timestamp(0),
  "cancelled_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "guest_return_request" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "guest_order_id" integer NOT NULL,
  "guest_name" varchar(100) NOT NULL,
  "guest_phone" varchar(20) NOT NULL,
  "request_type" "ReturnType" NOT NULL,
  "reason" text NOT NULL,
  "reason_detail" text,
  "refund_amount" decimal(12,2) NOT NULL,
  "refund_method" "RefundMethod" NOT NULL,
  "bank_name" varchar(50),
  "account_number" varchar(50),
  "account_holder" varchar(50),
  "status" "ReturnStatus" NOT NULL DEFAULT 'REQUESTED'::"ReturnStatus",
  "images" text,
  "admin_memo" text,
  "requested_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "processed_at" timestamp(0),
  "completed_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "inbox_message" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "channel" "MessageChannel" NOT NULL,
  "direction" "MessageDirection" NOT NULL,
  "thread_id" varchar(255) NOT NULL,
  "sender_id" varchar(255) NOT NULL,
  "sender_name" varchar(255),
  "content" text NOT NULL,
  "intent" varchar(50),
  "confidence" double precision,
  "ai_reply" text,
  "is_auto_replied" boolean NOT NULL DEFAULT false,
  "is_escalated" boolean NOT NULL DEFAULT false,
  "escalate_reason" varchar(255),
  "is_read" boolean NOT NULL DEFAULT false,
  "order_id" integer,
  "product_id" integer,
  "customer_id" integer,
  "metadata" jsonb,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "replied_at" timestamp(0),
  PRIMARY KEY ("id")
);
CREATE TABLE "auto_reply_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "intent" varchar(50) NOT NULL,
  "is_enabled" boolean NOT NULL DEFAULT true,
  "template" text,
  "ai_prompt_hint" text,
  "escalate_always" boolean NOT NULL DEFAULT false,
  "reply_delay_sec" integer NOT NULL DEFAULT 30,
  "max_auto_retries" integer NOT NULL DEFAULT 2,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "inquiry" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "inquiry_type" "InquiryType" NOT NULL,
  "title" varchar(200) NOT NULL,
  "content" text NOT NULL,
  "is_private" boolean NOT NULL DEFAULT false,
  "status" "InquiryStatus" NOT NULL DEFAULT 'PENDING'::"InquiryStatus",
  "admin_reply" text,
  "replied_at" timestamp(0),
  "replied_by" integer,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "shop_id" integer,
  "shop_product_id" integer,
  PRIMARY KEY ("id")
);
CREATE TABLE "inquiry_reply" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "inquiry_id" integer NOT NULL,
  "content" text NOT NULL,
  "is_admin" boolean NOT NULL DEFAULT true,
  "admin_id" integer,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "kakao_ad_batch" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "date" varchar(10) NOT NULL,
  "card_count" integer NOT NULL DEFAULT 0,
  "sent_count" integer NOT NULL DEFAULT 0,
  "failed_count" integer NOT NULL DEFAULT 0,
  "total_duration_sec" integer,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "kakao_ad_card" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "batch_id" integer,
  "title" varchar(100) NOT NULL,
  "title_color" varchar(20) NOT NULL DEFAULT 'red',
  "subtitle" varchar(200) NOT NULL,
  "banner_text" varchar(200),
  "ribbon_text" varchar(50),
  "sale_badge" boolean NOT NULL DEFAULT false,
  "product_name" varchar(300) NOT NULL,
  "description_html" text NOT NULL,
  "price_text" varchar(200) NOT NULL,
  "source_image_url" varchar(1000) NOT NULL,
  "rendered_png_path" varchar(500),
  "ai_generated" boolean NOT NULL DEFAULT true,
  "edited_at" timestamp(0),
  "ai_tokens_used" integer,
  "send_status" "KakaoSendStatus" NOT NULL DEFAULT 'DRAFT'::"KakaoSendStatus",
  "sent_at" timestamp(0),
  "kakao_message_id" varchar(100),
  "send_error" varchar(500),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "legacy_order" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "order_date" date NOT NULL,
  "channel_name" varchar(50) NOT NULL,
  "product_name" varchar(500) NOT NULL,
  "quantity" integer NOT NULL DEFAULT 1,
  "sale_price" integer NOT NULL DEFAULT 0,
  "cost_price" integer NOT NULL DEFAULT 0,
  "profit" integer NOT NULL DEFAULT 0,
  "buyer_hash" varchar(64),
  "region_code" varchar(30),
  "raw_sheet_name" varchar(50) NOT NULL,
  "source_file" varchar(200) NOT NULL,
  "row_index" integer NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "order_event" (
  "id" text NOT NULL,
  "order_id" integer NOT NULL,
  "type" varchar(50) NOT NULL,
  "payload" jsonb NOT NULL,
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "coaching_tip" (
  "id" text NOT NULL,
  "user_id" integer NOT NULL,
  "rule_key" varchar(100) NOT NULL,
  "message" text NOT NULL,
  "cta_url" varchar(500),
  "shown" boolean NOT NULL DEFAULT false,
  "shown_at" timestamp(3),
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "mission" (
  "id" text NOT NULL,
  "code" varchar(100) NOT NULL,
  "title" varchar(200) NOT NULL,
  "description" text NOT NULL,
  "target_value" integer NOT NULL DEFAULT 1,
  "reward_type" varchar(50) NOT NULL,
  "reward_value" varchar(200) NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "user_mission" (
  "user_id" integer NOT NULL,
  "mission_id" text NOT NULL,
  "progress" integer NOT NULL DEFAULT 0,
  "completed" boolean NOT NULL DEFAULT false,
  "completed_at" timestamp(3),
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("user_id", "mission_id")
);
CREATE TABLE "lite_auto_publish_config" (
  "user_id" integer NOT NULL,
  "publish_hour" integer NOT NULL DEFAULT 10,
  "publish_minute" integer NOT NULL DEFAULT 0,
  "daily_count" integer NOT NULL DEFAULT 20,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_run_at" timestamp(3),
  "created_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("user_id")
);
CREATE TABLE "lite_auto_publish_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "shop_id" integer NOT NULL,
  "published_at" timestamp(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "product_ids" jsonb NOT NULL,
  "count" integer NOT NULL,
  "status" varchar(20) NOT NULL,
  "error_message" text,
  PRIMARY KEY ("id")
);
CREATE TABLE "notification" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "shop_id" integer,
  "section" varchar(20) NOT NULL DEFAULT 'shop',
  "type" "NotificationType" NOT NULL,
  "title" varchar(255) NOT NULL,
  "message" text NOT NULL,
  "metadata" jsonb,
  "is_read" boolean NOT NULL DEFAULT false,
  "link" varchar(500),
  "order_id" integer,
  "inquiry_id" integer,
  "settlement_id" integer,
  "return_request_id" integer,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "read_at" timestamp(0),
  PRIMARY KEY ("id")
);
CREATE TABLE "order" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "order_number" varchar(50) NOT NULL,
  "status" "CustomerOrderStatus" NOT NULL DEFAULT 'PENDING'::"CustomerOrderStatus",
  "subtotal_amount" decimal(12,2) NOT NULL,
  "discount_amount" decimal(10,2) NOT NULL DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL,
  "ordered_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "paid_at" timestamp(0),
  "preparing_at" timestamp(0),
  "shipped_at" timestamp(0),
  "delivered_at" timestamp(0),
  "cancelled_at" timestamp(0),
  "cancel_reason" varchar(500),
  "cancelled_by" varchar(20),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "shop_id" integer,
  "source" "OrderSource" NOT NULL DEFAULT 'SHOP'::"OrderSource",
  "wholesale_order_status" "WholesaleOrderStatus",
  "wholesale_channel_id" integer,
  "wholesale_ordered_at" timestamp(0),
  "external_kind" "ExternalOrderKind",
  "external_memo" text,
  "admin_memo" text,
  "admin_memo_updated_at" timestamp(0),
  "order_type" varchar(20) NOT NULL DEFAULT 'RETAIL',
  PRIMARY KEY ("id")
);
CREATE TABLE "order_item" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "order_id" integer NOT NULL,
  "shop_product_id" integer NOT NULL,
  "variant_id" integer,
  "product_name" varchar(500) NOT NULL,
  "option_summary" varchar(500),
  "thumbnail_url" varchar(1000),
  "quantity" integer NOT NULL,
  "unit_price" decimal(12,2) NOT NULL,
  "total_price" decimal(12,2) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "page_generation_job" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "source_type" varchar(20) NOT NULL,
  "source_url" varchar(1000),
  "source_html" text,
  "source_files" jsonb,
  "extracted_data" jsonb,
  "screenshot" text,
  "layout_analysis" jsonb,
  "generated_html" text,
  "generated_css" text,
  "preview_image" varchar(1000),
  "template_id" integer,
  "status" varchar(20) NOT NULL DEFAULT 'pending',
  "error_message" text,
  "product_id" integer,
  "shop_id" integer,
  "created_by" integer NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "page_template" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "type" varchar(20) NOT NULL,
  "category" varchar(50),
  "html_template" text NOT NULL,
  "css_styles" text,
  "thumbnail" varchar(1000),
  "variables" jsonb,
  "color_scheme" jsonb,
  "is_active" boolean NOT NULL DEFAULT true,
  "is_default" boolean NOT NULL DEFAULT false,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "generated_page" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "shop_id" integer NOT NULL,
  "type" varchar(20) NOT NULL,
  "slug" varchar(200) NOT NULL,
  "title" varchar(500) NOT NULL,
  "html_content" text NOT NULL,
  "css_content" text,
  "meta_title" varchar(500),
  "meta_desc" varchar(1000),
  "og_image" varchar(1000),
  "product_id" integer,
  "is_published" boolean NOT NULL DEFAULT false,
  "published_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "payment" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "order_id" integer NOT NULL,
  "payment_key" varchar(200) NOT NULL,
  "toss_order_id" varchar(100) NOT NULL,
  "method" "TossPaymentMethod" NOT NULL,
  "status" "TossPaymentStatus" NOT NULL DEFAULT 'READY'::"TossPaymentStatus",
  "amount" decimal(12,2) NOT NULL,
  "virtual_account_number" varchar(50),
  "virtual_account_bank" varchar(20),
  "virtual_account_due_date" timestamp(0),
  "card_company" varchar(50),
  "card_number" varchar(20),
  "installment_month" integer,
  "cancel_reason" varchar(500),
  "cancelled_amount" decimal(12,2),
  "raw_response" text,
  "approved_at" timestamp(0),
  "cancelled_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "terms_policy" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "main" integer NOT NULL DEFAULT 0,
  "sub" integer NOT NULL DEFAULT 1,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "privacy_policy" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" varchar(255) NOT NULL,
  "content" text NOT NULL,
  "main" integer NOT NULL DEFAULT 0,
  "sub" integer NOT NULL DEFAULT 1,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "collected_post" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "external_id" varchar(255) NOT NULL,
  "title" varchar(500) NOT NULL,
  "content" text NOT NULL,
  "author" varchar(100),
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "channel_id" integer NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "collected_post_image" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "collected_post_id" integer NOT NULL,
  "url" varchar(1000) NOT NULL,
  "file_size" integer,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "file_hash" varchar(64),
  "file_name" varchar(255),
  PRIMARY KEY ("id")
);
CREATE TABLE "collected_post_comment" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "collected_post_id" integer NOT NULL,
  "author" varchar(100) NOT NULL,
  "content" text NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_sales_daily" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "date" date NOT NULL,
  "order_type" varchar(20) NOT NULL DEFAULT 'RETAIL',
  "qty" integer NOT NULL DEFAULT 0,
  "revenue" decimal(14,2) NOT NULL DEFAULT 0,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "product" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "channel_id" integer,
  "collected_post_id" integer,
  "name" varchar(500) NOT NULL,
  "source_product_name" varchar(500),
  "description" text,
  "thumbnail_url" varchar(1000),
  "category_id" varchar(100),
  "currency" varchar(10) NOT NULL DEFAULT 'KRW',
  "wholesale_price" decimal(12,2),
  "price" integer,
  "is_active" boolean NOT NULL DEFAULT true,
  "source_status" "SourceStatus" NOT NULL DEFAULT 'ACTIVE'::"SourceStatus",
  "sold_out_at" timestamp(0),
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  "republished_at" timestamp(0),
  "last_digest_published_at" timestamp(0),
  "shipping_fee" integer,
  "shipping_info" text,
  "bundle_max_qty" integer DEFAULT 1,
  "bundle_shipping_type" "BundleShippingType" NOT NULL DEFAULT 'NONE'::"BundleShippingType",
  PRIMARY KEY ("id")
);
CREATE TABLE "product_variant" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "option_summary" varchar(500),
  "price" integer NOT NULL,
  "wholesale_price" decimal(12,2),
  "bundle_unit" integer NOT NULL DEFAULT 1,
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_option" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "group_name" varchar(100) NOT NULL,
  "value" varchar(200) NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_image" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "url" varchar(1000) NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "file_hash" varchar(64),
  "file_name" varchar(255),
  "file_size" integer,
  "is_price_banner" boolean,
  PRIMARY KEY ("id")
);
CREATE TABLE "refund_account" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "order_id" integer,
  "guest_order_id" integer,
  "bank_name" varchar(50) NOT NULL,
  "account_number" varchar(50) NOT NULL,
  "account_holder" varchar(50) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "return_request" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "order_id" integer NOT NULL,
  "request_type" "ReturnType" NOT NULL,
  "reason" text NOT NULL,
  "reason_detail" text,
  "refund_amount" decimal(12,2) NOT NULL,
  "refund_method" "RefundMethod" NOT NULL,
  "bank_name" varchar(50),
  "account_number" varchar(50),
  "account_holder" varchar(50),
  "status" "ReturnStatus" NOT NULL DEFAULT 'REQUESTED'::"ReturnStatus",
  "images" text,
  "admin_memo" text,
  "requested_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "processed_at" timestamp(0),
  "completed_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "review" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "order_item_id" integer NOT NULL,
  "rating" integer NOT NULL,
  "title" varchar(200),
  "content" text NOT NULL,
  "images" text,
  "is_visible" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "settlement" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "shop_id" integer NOT NULL,
  "period_start" date NOT NULL,
  "period_end" date NOT NULL,
  "total_orders" integer NOT NULL DEFAULT 0,
  "total_amount" decimal(12,2) NOT NULL DEFAULT 0,
  "status" "SettlementStatus" NOT NULL DEFAULT 'PENDING'::"SettlementStatus",
  "memo" varchar(500),
  "settled_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "settlement_item" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "settlement_id" integer NOT NULL,
  "order_item_id" integer,
  "order_id" integer,
  "guest_order_item_id" integer,
  "guest_order_id" integer,
  "quantity" integer NOT NULL,
  "unit_price" decimal(10,2) NOT NULL,
  "total_price" decimal(12,2) NOT NULL,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "shipping_address" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "order_id" integer,
  "guest_order_id" integer,
  "recipient_name" varchar(100) NOT NULL,
  "recipient_phone" varchar(20) NOT NULL,
  "postal_code" varchar(10) NOT NULL,
  "address" varchar(500) NOT NULL,
  "address_detail" varchar(500),
  "delivery_memo" varchar(500),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "shop_product" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "product_id" integer,
  "shop_id" integer NOT NULL,
  "published_at" timestamp(0),
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "shop" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "subdomain" varchar(63) NOT NULL,
  "name" varchar(255) NOT NULL,
  "cover_url" varchar(500),
  "bank_name" varchar(50),
  "bank_account" varchar(50),
  "account_holder" varchar(100),
  "contact_phone" varchar(20),
  "contact_email" varchar(255),
  "owner_name" varchar(100),
  "business_number" varchar(20),
  "manager_name" varchar(100),
  "manager_phone" varchar(20),
  "manager_email" varchar(255),
  "admin_login_id" varchar(50),
  "admin_login_password" varchar(255),
  "is_active" boolean NOT NULL DEFAULT true,
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "shop_theme" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "shop_id" integer NOT NULL,
  "primary_color" varchar(20),
  "secondary_color" varchar(20),
  "logo_url" varchar(500),
  "favicon_url" varchar(500),
  "banner_url" varchar(500),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "source_snapshot" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "collected_post_id" integer NOT NULL,
  "status" "SourceStatus" NOT NULL DEFAULT 'ACTIVE'::"SourceStatus",
  "wholesale_price" decimal(12,2),
  "raw_text" text,
  "checked_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "price_history" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "old_wholesale_price" decimal(12,2),
  "new_wholesale_price" decimal(12,2),
  "old_price" integer,
  "new_price" integer,
  "applied" boolean NOT NULL DEFAULT false,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "product_duplicate" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "product_id" integer NOT NULL,
  "dup_product_id" integer NOT NULL,
  "method" varchar(30) NOT NULL,
  "similarity" double precision NOT NULL,
  "resolved" boolean NOT NULL DEFAULT false,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "subscription_plan" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "slug" varchar(50) NOT NULL,
  "name" varchar(100) NOT NULL,
  "price_monthly" integer NOT NULL DEFAULT 0,
  "price_yearly" integer NOT NULL DEFAULT 0,
  "features" text NOT NULL,
  "limits" text NOT NULL,
  "sort_order" integer NOT NULL DEFAULT 0,
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "user_subscription" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "plan_id" integer NOT NULL,
  "status" "SubscriptionStatus" NOT NULL DEFAULT 'ACTIVE'::"SubscriptionStatus",
  "period_start" timestamp(0) NOT NULL,
  "period_end" timestamp(0) NOT NULL,
  "payment_method" varchar(50),
  "cancel_at_period_end" boolean NOT NULL DEFAULT false,
  "cancelled_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "usage_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "date" date NOT NULL,
  "ai_calls" integer NOT NULL DEFAULT 0,
  "collections" integer NOT NULL DEFAULT 0,
  "publishes" integer NOT NULL DEFAULT 0,
  "api_calls" integer NOT NULL DEFAULT 0,
  "storage_mb" integer NOT NULL DEFAULT 0,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL,
  PRIMARY KEY ("id")
);
CREATE TABLE "user" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "email" varchar(255) NOT NULL,
  "password" varchar(255),
  "name" varchar(100),
  "phone" varchar(20),
  "company_name" varchar(200),
  "business_number" varchar(30),
  "online_sales_number" varchar(50),
  "seller_type" varchar(30),
  "role" "UserRole" NOT NULL DEFAULT 'USER'::"UserRole",
  "profile_image" varchar(500),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "marketing_agreed_at" timestamp(0),
  "privacy_agreed_at" timestamp(0),
  "signup_completed_at" timestamp(0),
  "tos_agreed_at" timestamp(0),
  "deleted_at" timestamp(0),
  "shop_id" integer,
  "mode" varchar(20) NOT NULL DEFAULT 'pro',
  "lite_start_at" timestamp(0),
  "pro_start_at" timestamp(0),
  "max_shops" integer NOT NULL DEFAULT 1,
  "manager_id" integer,
  "band_login_email" varchar(255),
  "extension_api_key" varchar(64),
  "extension_api_key_created_at" timestamp(3),
  "b2b_status" "B2bStatus" NOT NULL DEFAULT 'NONE'::"B2bStatus",
  "b2b_applied_at" timestamp(0),
  "b2b_approved_at" timestamp(0),
  "b2b_reject_reason" varchar(500),
  PRIMARY KEY ("id")
);
CREATE TABLE "user_login_log" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer,
  "provider" varchar(50) NOT NULL,
  "email" varchar(255),
  "ip" varchar(100),
  "user_agent" varchar(500),
  "success" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "sourcing_api_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "platform" "SourcingPlatform" NOT NULL,
  "api_key" varchar(500),
  "access_token" text,
  "refresh_token" text,
  "token_expiry" timestamp(0),
  "metadata" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "last_synced_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "band_cookie_expiry" timestamp(0),
  "band_session_cookie" text,
  "use_global_token" boolean NOT NULL DEFAULT false,
  PRIMARY KEY ("id")
);
CREATE TABLE "ai_api_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "provider" "AiProvider" NOT NULL,
  "api_key" varchar(500) NOT NULL,
  "model" varchar(100) NOT NULL,
  "config" text,
  "is_active" boolean NOT NULL DEFAULT true,
  "usage_count" integer NOT NULL DEFAULT 0,
  "daily_usage_count" integer NOT NULL DEFAULT 0,
  "daily_reset_date" date,
  "last_used_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "ai_prompt_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "prompt_type" varchar(50) NOT NULL,
  "name" varchar(100) NOT NULL,
  "prompt" text NOT NULL,
  "description" varchar(500),
  "is_active" boolean NOT NULL DEFAULT true,
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "google_sheet_config" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "service_account_json" text NOT NULL,
  "spreadsheet_id" varchar(255) NOT NULL,
  "sheet_name" varchar(100),
  "is_active" boolean NOT NULL DEFAULT true,
  "last_synced_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "wholesale_band_catalog" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "band_key" varchar(255) NOT NULL,
  "band_no" integer,
  "name" varchar(255) NOT NULL,
  "description" text,
  "cover_url" varchar(500),
  "is_active" boolean NOT NULL DEFAULT true,
  "sort_order" integer NOT NULL DEFAULT 0,
  "created_by_id" integer,
  "source_channel_id" integer,
  "deleted_at" timestamp(0),
  "created_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);
CREATE TABLE "wishlist" (
  "id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" integer NOT NULL,
  "product_id" integer NOT NULL,
  "added_at" timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
);