SET search_path TO goodfood;
ALTER TABLE "user_address" ADD CONSTRAINT "user_address_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "agent_tasks" ADD CONSTRAINT "agent_tasks_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "agent_definitions" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "agent_logs" ADD CONSTRAINT "agent_logs_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "agent_definitions" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "agent_kpi_records" ADD CONSTRAINT "agent_kpi_records_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "agent_definitions" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "agent_workflow_steps" ADD CONSTRAINT "agent_workflow_steps_workflowId_fkey" FOREIGN KEY ("workflowId") REFERENCES "agent_workflows" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "agent_workflow_steps" ADD CONSTRAINT "agent_workflow_steps_agentId_fkey" FOREIGN KEY ("agentId") REFERENCES "agent_definitions" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "api_token" ADD CONSTRAINT "api_token_client_id_fkey" FOREIGN KEY ("client_id") REFERENCES "api_client" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "pricing_policy" ADD CONSTRAINT "pricing_policy_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pricing_policy" ADD CONSTRAINT "pricing_policy_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pricing_policy_target" ADD CONSTRAINT "pricing_policy_target_pricing_policy_id_fkey" FOREIGN KEY ("pricing_policy_id") REFERENCES "pricing_policy" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "pricing_policy_target" ADD CONSTRAINT "pricing_policy_target_retail_channel_id_fkey" FOREIGN KEY ("retail_channel_id") REFERENCES "channel" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "automation_config" ADD CONSTRAINT "automation_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workflow_log" ADD CONSTRAINT "workflow_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "workflow_step_log" ADD CONSTRAINT "workflow_step_log_workflow_id_fkey" FOREIGN KEY ("workflow_id") REFERENCES "workflow_log" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "band_notice_config" ADD CONSTRAINT "band_notice_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "bank_transaction" ADD CONSTRAINT "bank_transaction_bank_account_id_fkey" FOREIGN KEY ("bank_account_id") REFERENCES "bank_account" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cart" ADD CONSTRAINT "cart_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "cart" ADD CONSTRAINT "cart_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_cart_id_fkey" FOREIGN KEY ("cart_id") REFERENCES "cart" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_shop_product_id_fkey" FOREIGN KEY ("shop_product_id") REFERENCES "shop_product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "cart_item" ADD CONSTRAINT "cart_item_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variant" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "category" ADD CONSTRAINT "category_parent_id_fkey" FOREIGN KEY ("parent_id") REFERENCES "category" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "channel_product" ADD CONSTRAINT "channel_product_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "channel_product" ADD CONSTRAINT "channel_product_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "channel_product" ADD CONSTRAINT "channel_product_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "channel" ADD CONSTRAINT "channel_catalog_id_fkey" FOREIGN KEY ("catalog_id") REFERENCES "wholesale_band_catalog" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "channel" ADD CONSTRAINT "channel_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "channel" ADD CONSTRAINT "channel_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collected_product" ADD CONSTRAINT "collected_product_collected_post_id_fkey" FOREIGN KEY ("collected_post_id") REFERENCES "collected_post" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collected_product" ADD CONSTRAINT "collected_product_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "user_coupon" ADD CONSTRAINT "user_coupon_coupon_id_fkey" FOREIGN KEY ("coupon_id") REFERENCES "coupon" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_coupon" ADD CONSTRAINT "user_coupon_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "external_mall_connection" ADD CONSTRAINT "external_mall_connection_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "external_sourced_product" ADD CONSTRAINT "external_sourced_product_connection_id_fkey" FOREIGN KEY ("connection_id") REFERENCES "external_mall_connection" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "external_sourced_product" ADD CONSTRAINT "external_sourced_product_checkout_connection_id_fkey" FOREIGN KEY ("checkout_connection_id") REFERENCES "external_mall_connection" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "external_sourced_product" ADD CONSTRAINT "external_sourced_product_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "external_order" ADD CONSTRAINT "external_order_checkout_connection_id_fkey" FOREIGN KEY ("checkout_connection_id") REFERENCES "external_mall_connection" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "external_order" ADD CONSTRAINT "external_order_sourced_product_id_fkey" FOREIGN KEY ("sourced_product_id") REFERENCES "external_sourced_product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guest_order" ADD CONSTRAINT "guest_order_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "guest_order" ADD CONSTRAINT "guest_order_wholesale_channel_id_fkey" FOREIGN KEY ("wholesale_channel_id") REFERENCES "channel" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "guest_order_item" ADD CONSTRAINT "guest_order_item_guest_order_id_fkey" FOREIGN KEY ("guest_order_id") REFERENCES "guest_order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "guest_order_item" ADD CONSTRAINT "guest_order_item_shop_product_id_fkey" FOREIGN KEY ("shop_product_id") REFERENCES "shop_product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "guest_order_item" ADD CONSTRAINT "guest_order_item_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variant" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "guest_payment" ADD CONSTRAINT "guest_payment_guest_order_id_fkey" FOREIGN KEY ("guest_order_id") REFERENCES "guest_order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inbox_message" ADD CONSTRAINT "inbox_message_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "auto_reply_config" ADD CONSTRAINT "auto_reply_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inquiry" ADD CONSTRAINT "inquiry_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "inquiry" ADD CONSTRAINT "inquiry_shop_product_id_fkey" FOREIGN KEY ("shop_product_id") REFERENCES "shop_product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "inquiry" ADD CONSTRAINT "inquiry_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "inquiry_reply" ADD CONSTRAINT "inquiry_reply_inquiry_id_fkey" FOREIGN KEY ("inquiry_id") REFERENCES "inquiry" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "kakao_ad_batch" ADD CONSTRAINT "kakao_ad_batch_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "kakao_ad_card" ADD CONSTRAINT "kakao_ad_card_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "kakao_ad_card" ADD CONSTRAINT "kakao_ad_card_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "kakao_ad_card" ADD CONSTRAINT "kakao_ad_card_batch_id_fkey" FOREIGN KEY ("batch_id") REFERENCES "kakao_ad_batch" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "order_event" ADD CONSTRAINT "order_event_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "coaching_tip" ADD CONSTRAINT "coaching_tip_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_mission" ADD CONSTRAINT "user_mission_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_mission" ADD CONSTRAINT "user_mission_mission_id_fkey" FOREIGN KEY ("mission_id") REFERENCES "mission" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "lite_auto_publish_config" ADD CONSTRAINT "lite_auto_publish_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "lite_auto_publish_log" ADD CONSTRAINT "lite_auto_publish_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notification" ADD CONSTRAINT "notification_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "notification" ADD CONSTRAINT "notification_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "order" ADD CONSTRAINT "order_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "order" ADD CONSTRAINT "order_wholesale_channel_id_fkey" FOREIGN KEY ("wholesale_channel_id") REFERENCES "channel" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "order" ADD CONSTRAINT "order_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_shop_product_id_fkey" FOREIGN KEY ("shop_product_id") REFERENCES "shop_product" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "order_item" ADD CONSTRAINT "order_item_variant_id_fkey" FOREIGN KEY ("variant_id") REFERENCES "product_variant" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "page_generation_job" ADD CONSTRAINT "page_generation_job_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "page_generation_job" ADD CONSTRAINT "page_generation_job_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "page_generation_job" ADD CONSTRAINT "page_generation_job_template_id_fkey" FOREIGN KEY ("template_id") REFERENCES "page_template" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "page_generation_job" ADD CONSTRAINT "page_generation_job_created_by_fkey" FOREIGN KEY ("created_by") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "generated_page" ADD CONSTRAINT "generated_page_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "generated_page" ADD CONSTRAINT "generated_page_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "payment" ADD CONSTRAINT "payment_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "order" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collected_post" ADD CONSTRAINT "collected_post_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collected_post" ADD CONSTRAINT "collected_post_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "collected_post_image" ADD CONSTRAINT "collected_post_image_collected_post_id_fkey" FOREIGN KEY ("collected_post_id") REFERENCES "collected_post" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "collected_post_comment" ADD CONSTRAINT "collected_post_comment_collected_post_id_fkey" FOREIGN KEY ("collected_post_id") REFERENCES "collected_post" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "product" ADD CONSTRAINT "product_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "channel" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "product" ADD CONSTRAINT "product_collected_post_id_fkey" FOREIGN KEY ("collected_post_id") REFERENCES "collected_post" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "product" ADD CONSTRAINT "product_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "product_variant" ADD CONSTRAINT "product_variant_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "product_option" ADD CONSTRAINT "product_option_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "product_image" ADD CONSTRAINT "product_image_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "refund_account" ADD CONSTRAINT "refund_account_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "refund_account" ADD CONSTRAINT "refund_account_guest_order_id_fkey" FOREIGN KEY ("guest_order_id") REFERENCES "guest_order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "return_request" ADD CONSTRAINT "return_request_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "review" ADD CONSTRAINT "review_order_item_id_fkey" FOREIGN KEY ("order_item_id") REFERENCES "order_item" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "review" ADD CONSTRAINT "review_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "settlement" ADD CONSTRAINT "settlement_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "settlement" ADD CONSTRAINT "settlement_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "settlement_item" ADD CONSTRAINT "settlement_item_settlement_id_fkey" FOREIGN KEY ("settlement_id") REFERENCES "settlement" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "shipping_address" ADD CONSTRAINT "shipping_address_guest_order_id_fkey" FOREIGN KEY ("guest_order_id") REFERENCES "guest_order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "shipping_address" ADD CONSTRAINT "shipping_address_order_id_fkey" FOREIGN KEY ("order_id") REFERENCES "order" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "shop_product" ADD CONSTRAINT "shop_product_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "shop_product" ADD CONSTRAINT "shop_product_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "shop_product" ADD CONSTRAINT "shop_product_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "shop" ADD CONSTRAINT "shop_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "shop_theme" ADD CONSTRAINT "shop_theme_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_subscription" ADD CONSTRAINT "user_subscription_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user_subscription" ADD CONSTRAINT "user_subscription_plan_id_fkey" FOREIGN KEY ("plan_id") REFERENCES "subscription_plan" ("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "usage_log" ADD CONSTRAINT "usage_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "user" ADD CONSTRAINT "user_shop_id_fkey" FOREIGN KEY ("shop_id") REFERENCES "shop" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "user" ADD CONSTRAINT "user_manager_id_fkey" FOREIGN KEY ("manager_id") REFERENCES "user" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "user_login_log" ADD CONSTRAINT "user_login_log_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "sourcing_api_config" ADD CONSTRAINT "sourcing_api_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ai_api_config" ADD CONSTRAINT "ai_api_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ai_prompt_config" ADD CONSTRAINT "ai_prompt_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "google_sheet_config" ADD CONSTRAINT "google_sheet_config_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "wishlist" ADD CONSTRAINT "wishlist_product_id_fkey" FOREIGN KEY ("product_id") REFERENCES "product" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "wishlist" ADD CONSTRAINT "wishlist_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "user" ("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE UNIQUE INDEX "agent_definitions_name_key" ON "agent_definitions" ("name");
CREATE UNIQUE INDEX "agent_kpi_records_agentId_metric_period_date_key" ON "agent_kpi_records" ("agentId", "metric", "period", "date");
CREATE UNIQUE INDEX "api_client_client_id_key" ON "api_client" ("client_id");
CREATE UNIQUE INDEX "api_token_access_token_key" ON "api_token" ("access_token");
CREATE UNIQUE INDEX "pricing_policy_target_pricing_policy_id_retail_channel_id_key" ON "pricing_policy_target" ("pricing_policy_id", "retail_channel_id");
CREATE UNIQUE INDEX "automation_config_user_id_key" ON "automation_config" ("user_id");
CREATE UNIQUE INDEX "workflow_step_log_workflow_id_step_type_key" ON "workflow_step_log" ("workflow_id", "step_type");
CREATE UNIQUE INDEX "band_notice_config_user_id_key" ON "band_notice_config" ("user_id");
CREATE UNIQUE INDEX "cart_session_id_shop_id_key" ON "cart" ("session_id", "shop_id");
CREATE UNIQUE INDEX "cart_item_cart_id_shop_product_id_variant_id_key" ON "cart_item" ("cart_id", "shop_product_id", "variant_id");
CREATE UNIQUE INDEX "category_code_key" ON "category" ("code");
CREATE UNIQUE INDEX "channel_product_product_id_channel_id_key" ON "channel_product" ("product_id", "channel_id");
CREATE UNIQUE INDEX "channel_user_id_channel_key_key" ON "channel" ("user_id", "channel_key");
CREATE UNIQUE INDEX "coupon_code_key" ON "coupon" ("code");
CREATE UNIQUE INDEX "user_coupon_user_id_coupon_id_key" ON "user_coupon" ("user_id", "coupon_id");
CREATE UNIQUE INDEX "external_sourced_product_connection_id_external_product_id_key" ON "external_sourced_product" ("connection_id", "external_product_id");
CREATE UNIQUE INDEX "guest_order_order_number_key" ON "guest_order" ("order_number");
CREATE UNIQUE INDEX "guest_payment_guest_order_id_key" ON "guest_payment" ("guest_order_id");
CREATE UNIQUE INDEX "auto_reply_config_user_id_intent_key" ON "auto_reply_config" ("user_id", "intent");
CREATE UNIQUE INDEX "kakao_ad_batch_user_id_date_key" ON "kakao_ad_batch" ("user_id", "date");
CREATE UNIQUE INDEX "legacy_order_order_date_row_index_channel_name_key" ON "legacy_order" ("order_date", "row_index", "channel_name");
CREATE UNIQUE INDEX "mission_code_key" ON "mission" ("code");
CREATE UNIQUE INDEX "order_order_number_key" ON "order" ("order_number");
CREATE UNIQUE INDEX "generated_page_shop_id_slug_key" ON "generated_page" ("shop_id", "slug");
CREATE UNIQUE INDEX "payment_order_id_key" ON "payment" ("order_id");
CREATE UNIQUE INDEX "payment_payment_key_key" ON "payment" ("payment_key");
CREATE UNIQUE INDEX "collected_post_channel_id_external_id_key" ON "collected_post" ("channel_id", "external_id");
CREATE UNIQUE INDEX "product_sales_daily_product_id_date_order_type_key" ON "product_sales_daily" ("product_id", "date", "order_type");
CREATE UNIQUE INDEX "refund_account_order_id_key" ON "refund_account" ("order_id");
CREATE UNIQUE INDEX "refund_account_guest_order_id_key" ON "refund_account" ("guest_order_id");
CREATE UNIQUE INDEX "review_order_item_id_key" ON "review" ("order_item_id");
CREATE UNIQUE INDEX "settlement_item_settlement_id_order_item_id_key" ON "settlement_item" ("settlement_id", "order_item_id");
CREATE UNIQUE INDEX "settlement_item_settlement_id_guest_order_item_id_key" ON "settlement_item" ("settlement_id", "guest_order_item_id");
CREATE UNIQUE INDEX "shipping_address_order_id_key" ON "shipping_address" ("order_id");
CREATE UNIQUE INDEX "shipping_address_guest_order_id_key" ON "shipping_address" ("guest_order_id");
CREATE UNIQUE INDEX "shop_product_product_id_shop_id_key" ON "shop_product" ("product_id", "shop_id");
CREATE UNIQUE INDEX "shop_subdomain_key" ON "shop" ("subdomain");
CREATE UNIQUE INDEX "shop_theme_shop_id_key" ON "shop_theme" ("shop_id");
CREATE UNIQUE INDEX "product_duplicate_product_id_dup_product_id_method_key" ON "product_duplicate" ("product_id", "dup_product_id", "method");
CREATE UNIQUE INDEX "subscription_plan_slug_key" ON "subscription_plan" ("slug");
CREATE UNIQUE INDEX "user_subscription_user_id_key" ON "user_subscription" ("user_id");
CREATE UNIQUE INDEX "usage_log_user_id_date_key" ON "usage_log" ("user_id", "date");
CREATE UNIQUE INDEX "user_email_key" ON "user" ("email");
CREATE UNIQUE INDEX "user_extension_api_key_key" ON "user" ("extension_api_key");
CREATE UNIQUE INDEX "sourcing_api_config_user_id_platform_key" ON "sourcing_api_config" ("user_id", "platform");
CREATE UNIQUE INDEX "ai_api_config_user_id_provider_key" ON "ai_api_config" ("user_id", "provider");
CREATE UNIQUE INDEX "ai_prompt_config_user_id_prompt_type_key" ON "ai_prompt_config" ("user_id", "prompt_type");
CREATE UNIQUE INDEX "google_sheet_config_user_id_key" ON "google_sheet_config" ("user_id");
CREATE UNIQUE INDEX "wholesale_band_catalog_band_key_key" ON "wholesale_band_catalog" ("band_key");
CREATE UNIQUE INDEX "wishlist_user_id_product_id_key" ON "wishlist" ("user_id", "product_id");
CREATE INDEX IF NOT EXISTS "user_address_user_id_idx" ON "user_address" ("user_id");
CREATE INDEX IF NOT EXISTS "user_address_user_id_is_default_idx" ON "user_address" ("user_id", "is_default");
CREATE INDEX IF NOT EXISTS "agent_definitions_layer_status_idx" ON "agent_definitions" ("layer", "status");
CREATE INDEX IF NOT EXISTS "agent_definitions_name_idx" ON "agent_definitions" ("name");
CREATE INDEX IF NOT EXISTS "agent_tasks_agentId_status_idx" ON "agent_tasks" ("agentId", "status");
CREATE INDEX IF NOT EXISTS "agent_tasks_eventType_createdAt_idx" ON "agent_tasks" ("eventType", "createdAt");
CREATE INDEX IF NOT EXISTS "agent_tasks_status_priority_createdAt_idx" ON "agent_tasks" ("status", "priority", "createdAt");
CREATE INDEX IF NOT EXISTS "agent_tasks_user_id_createdAt_idx" ON "agent_tasks" ("user_id", "createdAt");
CREATE INDEX IF NOT EXISTS "agent_logs_agentId_level_createdAt_idx" ON "agent_logs" ("agentId", "level", "createdAt");
CREATE INDEX IF NOT EXISTS "agent_logs_taskId_idx" ON "agent_logs" ("taskId");
CREATE INDEX IF NOT EXISTS "agent_logs_user_id_createdAt_idx" ON "agent_logs" ("user_id", "createdAt");
CREATE INDEX IF NOT EXISTS "agent_kpi_records_agentId_metric_date_idx" ON "agent_kpi_records" ("agentId", "metric", "date");
CREATE INDEX IF NOT EXISTS "agent_workflows_triggerEvent_isActive_idx" ON "agent_workflows" ("triggerEvent", "isActive");
CREATE INDEX IF NOT EXISTS "agent_workflow_steps_workflowId_order_idx" ON "agent_workflow_steps" ("workflowId", "order");
CREATE INDEX IF NOT EXISTS "sourcing_conditions_user_id_is_active_idx" ON "sourcing_conditions" ("user_id", "is_active");
CREATE INDEX IF NOT EXISTS "api_client_user_id_idx" ON "api_client" ("user_id");
CREATE INDEX IF NOT EXISTS "api_token_expires_at_idx" ON "api_token" ("expires_at");
CREATE INDEX IF NOT EXISTS "api_call_log_client_id_created_at_idx" ON "api_call_log" ("client_id", "created_at");
CREATE INDEX IF NOT EXISTS "pricing_policy_user_id_idx" ON "pricing_policy" ("user_id");
CREATE INDEX IF NOT EXISTS "pricing_policy_channel_id_idx" ON "pricing_policy" ("channel_id");
CREATE INDEX IF NOT EXISTS "pricing_policy_target_retail_channel_id_idx" ON "pricing_policy_target" ("retail_channel_id");
CREATE INDEX IF NOT EXISTS "automation_config_is_enabled_idx" ON "automation_config" ("is_enabled");
CREATE INDEX IF NOT EXISTS "workflow_log_user_id_workflow_type_started_at_idx" ON "workflow_log" ("user_id", "workflow_type", "started_at");
CREATE INDEX IF NOT EXISTS "workflow_log_status_idx" ON "workflow_log" ("status");
CREATE INDEX IF NOT EXISTS "workflow_log_trigger_type_idx" ON "workflow_log" ("trigger_type");
CREATE INDEX IF NOT EXISTS "workflow_step_log_workflow_id_idx" ON "workflow_step_log" ("workflow_id");
CREATE INDEX IF NOT EXISTS "workflow_step_log_status_idx" ON "workflow_step_log" ("status");
CREATE INDEX IF NOT EXISTS "workflow_step_log_deleted_at_idx" ON "workflow_step_log" ("deleted_at");
CREATE INDEX IF NOT EXISTS "band_notice_config_is_enabled_idx" ON "band_notice_config" ("is_enabled");
CREATE INDEX IF NOT EXISTS "bank_account_user_id_idx" ON "bank_account" ("user_id");
CREATE INDEX IF NOT EXISTS "bank_account_user_id_is_active_idx" ON "bank_account" ("user_id", "is_active");
CREATE INDEX IF NOT EXISTS "bank_transaction_bank_account_id_idx" ON "bank_transaction" ("bank_account_id");
CREATE INDEX IF NOT EXISTS "bank_transaction_transaction_date_idx" ON "bank_transaction" ("transaction_date");
CREATE INDEX IF NOT EXISTS "bank_transaction_matched_order_id_idx" ON "bank_transaction" ("matched_order_id");
CREATE INDEX IF NOT EXISTS "bank_transaction_sender_name_idx" ON "bank_transaction" ("sender_name");
CREATE INDEX IF NOT EXISTS "cart_session_id_idx" ON "cart" ("session_id");
CREATE INDEX IF NOT EXISTS "cart_user_id_idx" ON "cart" ("user_id");
CREATE INDEX IF NOT EXISTS "cart_shop_id_idx" ON "cart" ("shop_id");
CREATE INDEX IF NOT EXISTS "cart_expires_at_idx" ON "cart" ("expires_at");
CREATE INDEX IF NOT EXISTS "cart_item_cart_id_idx" ON "cart_item" ("cart_id");
CREATE INDEX IF NOT EXISTS "cart_item_shop_product_id_idx" ON "cart_item" ("shop_product_id");
CREATE INDEX IF NOT EXISTS "cart_item_variant_id_idx" ON "cart_item" ("variant_id");
CREATE INDEX IF NOT EXISTS "category_parent_id_idx" ON "category" ("parent_id");
CREATE INDEX IF NOT EXISTS "category_is_active_idx" ON "category" ("is_active");
CREATE INDEX IF NOT EXISTS "channel_product_user_id_idx" ON "channel_product" ("user_id");
CREATE INDEX IF NOT EXISTS "channel_product_product_id_idx" ON "channel_product" ("product_id");
CREATE INDEX IF NOT EXISTS "channel_product_channel_id_idx" ON "channel_product" ("channel_id");
CREATE INDEX IF NOT EXISTS "channel_product_deleted_at_idx" ON "channel_product" ("deleted_at");
CREATE INDEX IF NOT EXISTS "channel_product_publish_batch_id_idx" ON "channel_product" ("publish_batch_id");
CREATE INDEX IF NOT EXISTS "channel_user_id_idx" ON "channel" ("user_id");
CREATE INDEX IF NOT EXISTS "channel_shop_id_idx" ON "channel" ("shop_id");
CREATE INDEX IF NOT EXISTS "channel_is_active_idx" ON "channel" ("is_active");
CREATE INDEX IF NOT EXISTS "channel_deleted_at_idx" ON "channel" ("deleted_at");
CREATE INDEX IF NOT EXISTS "channel_kind_platform_idx" ON "channel" ("kind", "platform");
CREATE INDEX IF NOT EXISTS "channel_catalog_id_idx" ON "channel" ("catalog_id");
CREATE INDEX IF NOT EXISTS "collected_product_user_id_idx" ON "collected_product" ("user_id");
CREATE INDEX IF NOT EXISTS "collected_product_collected_post_id_idx" ON "collected_product" ("collected_post_id");
CREATE INDEX IF NOT EXISTS "collected_product_deleted_at_idx" ON "collected_product" ("deleted_at");
CREATE INDEX IF NOT EXISTS "coupon_code_idx" ON "coupon" ("code");
CREATE INDEX IF NOT EXISTS "coupon_is_active_idx" ON "coupon" ("is_active");
CREATE INDEX IF NOT EXISTS "coupon_valid_from_valid_until_idx" ON "coupon" ("valid_from", "valid_until");
CREATE INDEX IF NOT EXISTS "user_coupon_user_id_idx" ON "user_coupon" ("user_id");
CREATE INDEX IF NOT EXISTS "user_coupon_coupon_id_idx" ON "user_coupon" ("coupon_id");
CREATE INDEX IF NOT EXISTS "user_coupon_is_used_idx" ON "user_coupon" ("is_used");
CREATE INDEX IF NOT EXISTS "user_coupon_user_id_is_used_idx" ON "user_coupon" ("user_id", "is_used");
CREATE INDEX IF NOT EXISTS "external_mall_connection_user_id_is_active_idx" ON "external_mall_connection" ("user_id", "is_active");
CREATE INDEX IF NOT EXISTS "external_mall_connection_platform_idx" ON "external_mall_connection" ("platform");
CREATE INDEX IF NOT EXISTS "external_mall_connection_purpose_idx" ON "external_mall_connection" ("purpose");
CREATE INDEX IF NOT EXISTS "external_sourced_product_user_id_idx" ON "external_sourced_product" ("user_id");
CREATE INDEX IF NOT EXISTS "external_sourced_product_product_id_idx" ON "external_sourced_product" ("product_id");
CREATE INDEX IF NOT EXISTS "external_sourced_product_checkout_connection_id_idx" ON "external_sourced_product" ("checkout_connection_id");
CREATE INDEX IF NOT EXISTS "external_order_user_id_status_idx" ON "external_order" ("user_id", "status");
CREATE INDEX IF NOT EXISTS "external_order_sourced_product_id_idx" ON "external_order" ("sourced_product_id");
CREATE INDEX IF NOT EXISTS "external_order_tracking_code_idx" ON "external_order" ("tracking_code");
CREATE INDEX IF NOT EXISTS "external_order_created_at_idx" ON "external_order" ("created_at");
CREATE INDEX IF NOT EXISTS "guest_order_shop_id_idx" ON "guest_order" ("shop_id");
CREATE INDEX IF NOT EXISTS "guest_order_order_number_idx" ON "guest_order" ("order_number");
CREATE INDEX IF NOT EXISTS "guest_order_status_idx" ON "guest_order" ("status");
CREATE INDEX IF NOT EXISTS "guest_order_guest_phone_idx" ON "guest_order" ("guest_phone");
CREATE INDEX IF NOT EXISTS "guest_order_ordered_at_idx" ON "guest_order" ("ordered_at");
CREATE INDEX IF NOT EXISTS "guest_order_paid_at_idx" ON "guest_order" ("paid_at");
CREATE INDEX IF NOT EXISTS "guest_order_delivered_at_idx" ON "guest_order" ("delivered_at");
CREATE INDEX IF NOT EXISTS "guest_order_shop_id_status_idx" ON "guest_order" ("shop_id", "status");
CREATE INDEX IF NOT EXISTS "guest_order_wholesale_order_status_idx" ON "guest_order" ("wholesale_order_status");
CREATE INDEX IF NOT EXISTS "guest_order_source_idx" ON "guest_order" ("source");
CREATE INDEX IF NOT EXISTS "guest_order_inbox_message_id_idx" ON "guest_order" ("inbox_message_id");
CREATE INDEX IF NOT EXISTS "guest_order_item_guest_order_id_idx" ON "guest_order_item" ("guest_order_id");
CREATE INDEX IF NOT EXISTS "guest_order_item_shop_product_id_idx" ON "guest_order_item" ("shop_product_id");
CREATE INDEX IF NOT EXISTS "guest_order_item_variant_id_idx" ON "guest_order_item" ("variant_id");
CREATE INDEX IF NOT EXISTS "guest_payment_guest_order_id_idx" ON "guest_payment" ("guest_order_id");
CREATE INDEX IF NOT EXISTS "guest_payment_payment_key_idx" ON "guest_payment" ("payment_key");
CREATE INDEX IF NOT EXISTS "guest_payment_toss_order_id_idx" ON "guest_payment" ("toss_order_id");
CREATE INDEX IF NOT EXISTS "guest_payment_status_idx" ON "guest_payment" ("status");
CREATE INDEX IF NOT EXISTS "guest_return_request_guest_order_id_idx" ON "guest_return_request" ("guest_order_id");
CREATE INDEX IF NOT EXISTS "guest_return_request_status_idx" ON "guest_return_request" ("status");
CREATE INDEX IF NOT EXISTS "inbox_message_user_id_channel_is_read_idx" ON "inbox_message" ("user_id", "channel", "is_read");
CREATE INDEX IF NOT EXISTS "inbox_message_user_id_is_escalated_idx" ON "inbox_message" ("user_id", "is_escalated");
CREATE INDEX IF NOT EXISTS "inbox_message_thread_id_idx" ON "inbox_message" ("thread_id");
CREATE INDEX IF NOT EXISTS "inbox_message_sender_id_idx" ON "inbox_message" ("sender_id");
CREATE INDEX IF NOT EXISTS "inbox_message_intent_idx" ON "inbox_message" ("intent");
CREATE INDEX IF NOT EXISTS "inbox_message_created_at_idx" ON "inbox_message" ("created_at");
CREATE INDEX IF NOT EXISTS "auto_reply_config_user_id_is_enabled_idx" ON "auto_reply_config" ("user_id", "is_enabled");
CREATE INDEX IF NOT EXISTS "inquiry_user_id_idx" ON "inquiry" ("user_id");
CREATE INDEX IF NOT EXISTS "inquiry_shop_id_idx" ON "inquiry" ("shop_id");
CREATE INDEX IF NOT EXISTS "inquiry_shop_product_id_idx" ON "inquiry" ("shop_product_id");
CREATE INDEX IF NOT EXISTS "inquiry_status_idx" ON "inquiry" ("status");
CREATE INDEX IF NOT EXISTS "inquiry_user_id_status_idx" ON "inquiry" ("user_id", "status");
CREATE INDEX IF NOT EXISTS "inquiry_reply_inquiry_id_idx" ON "inquiry_reply" ("inquiry_id");
CREATE INDEX IF NOT EXISTS "kakao_ad_batch_user_id_idx" ON "kakao_ad_batch" ("user_id");
CREATE INDEX IF NOT EXISTS "kakao_ad_batch_date_idx" ON "kakao_ad_batch" ("date");
CREATE INDEX IF NOT EXISTS "kakao_ad_card_user_id_idx" ON "kakao_ad_card" ("user_id");
CREATE INDEX IF NOT EXISTS "kakao_ad_card_product_id_idx" ON "kakao_ad_card" ("product_id");
CREATE INDEX IF NOT EXISTS "kakao_ad_card_batch_id_idx" ON "kakao_ad_card" ("batch_id");
CREATE INDEX IF NOT EXISTS "kakao_ad_card_send_status_idx" ON "kakao_ad_card" ("send_status");
CREATE INDEX IF NOT EXISTS "kakao_ad_card_created_at_idx" ON "kakao_ad_card" ("created_at");
CREATE INDEX IF NOT EXISTS "legacy_order_order_date_idx" ON "legacy_order" ("order_date");
CREATE INDEX IF NOT EXISTS "legacy_order_product_name_idx" ON "legacy_order" ("product_name");
CREATE INDEX IF NOT EXISTS "legacy_order_channel_name_idx" ON "legacy_order" ("channel_name");
CREATE INDEX IF NOT EXISTS "order_event_order_id_idx" ON "order_event" ("order_id");
CREATE INDEX IF NOT EXISTS "order_event_type_idx" ON "order_event" ("type");
CREATE INDEX IF NOT EXISTS "order_event_created_at_idx" ON "order_event" ("created_at");
CREATE INDEX IF NOT EXISTS "coaching_tip_user_id_shown_idx" ON "coaching_tip" ("user_id", "shown");
CREATE INDEX IF NOT EXISTS "coaching_tip_rule_key_idx" ON "coaching_tip" ("rule_key");
CREATE INDEX IF NOT EXISTS "coaching_tip_created_at_idx" ON "coaching_tip" ("created_at");
CREATE INDEX IF NOT EXISTS "mission_code_idx" ON "mission" ("code");
CREATE INDEX IF NOT EXISTS "mission_is_active_sort_order_idx" ON "mission" ("is_active", "sort_order");
CREATE INDEX IF NOT EXISTS "user_mission_user_id_completed_idx" ON "user_mission" ("user_id", "completed");
CREATE INDEX IF NOT EXISTS "user_mission_mission_id_idx" ON "user_mission" ("mission_id");
CREATE INDEX IF NOT EXISTS "lite_auto_publish_config_is_active_publish_hour_publish_minu" ON "lite_auto_publish_config" ("is_active", "publish_hour", "publish_minute");
CREATE INDEX IF NOT EXISTS "lite_auto_publish_log_user_id_published_at_idx" ON "lite_auto_publish_log" ("user_id", "published_at");
CREATE INDEX IF NOT EXISTS "lite_auto_publish_log_status_idx" ON "lite_auto_publish_log" ("status");
CREATE INDEX IF NOT EXISTS "notification_user_id_idx" ON "notification" ("user_id");
CREATE INDEX IF NOT EXISTS "notification_shop_id_idx" ON "notification" ("shop_id");
CREATE INDEX IF NOT EXISTS "notification_section_idx" ON "notification" ("section");
CREATE INDEX IF NOT EXISTS "notification_is_read_idx" ON "notification" ("is_read");
CREATE INDEX IF NOT EXISTS "notification_type_idx" ON "notification" ("type");
CREATE INDEX IF NOT EXISTS "notification_created_at_idx" ON "notification" ("created_at");
CREATE INDEX IF NOT EXISTS "order_user_id_idx" ON "order" ("user_id");
CREATE INDEX IF NOT EXISTS "order_shop_id_idx" ON "order" ("shop_id");
CREATE INDEX IF NOT EXISTS "order_order_number_idx" ON "order" ("order_number");
CREATE INDEX IF NOT EXISTS "order_status_idx" ON "order" ("status");
CREATE INDEX IF NOT EXISTS "order_ordered_at_idx" ON "order" ("ordered_at");
CREATE INDEX IF NOT EXISTS "order_paid_at_idx" ON "order" ("paid_at");
CREATE INDEX IF NOT EXISTS "order_delivered_at_idx" ON "order" ("delivered_at");
CREATE INDEX IF NOT EXISTS "order_user_id_status_idx" ON "order" ("user_id", "status");
CREATE INDEX IF NOT EXISTS "order_shop_id_status_idx" ON "order" ("shop_id", "status");
CREATE INDEX IF NOT EXISTS "order_wholesale_order_status_idx" ON "order" ("wholesale_order_status");
CREATE INDEX IF NOT EXISTS "order_source_idx" ON "order" ("source");
CREATE INDEX IF NOT EXISTS "order_item_order_id_idx" ON "order_item" ("order_id");
CREATE INDEX IF NOT EXISTS "order_item_shop_product_id_idx" ON "order_item" ("shop_product_id");
CREATE INDEX IF NOT EXISTS "order_item_variant_id_idx" ON "order_item" ("variant_id");
CREATE INDEX IF NOT EXISTS "page_generation_job_created_by_created_at_idx" ON "page_generation_job" ("created_by", "created_at");
CREATE INDEX IF NOT EXISTS "page_generation_job_status_idx" ON "page_generation_job" ("status");
CREATE INDEX IF NOT EXISTS "page_generation_job_shop_id_idx" ON "page_generation_job" ("shop_id");
CREATE INDEX IF NOT EXISTS "page_generation_job_product_id_idx" ON "page_generation_job" ("product_id");
CREATE INDEX IF NOT EXISTS "page_template_type_is_active_idx" ON "page_template" ("type", "is_active");
CREATE INDEX IF NOT EXISTS "generated_page_shop_id_type_is_published_idx" ON "generated_page" ("shop_id", "type", "is_published");
CREATE INDEX IF NOT EXISTS "payment_payment_key_idx" ON "payment" ("payment_key");
CREATE INDEX IF NOT EXISTS "payment_toss_order_id_idx" ON "payment" ("toss_order_id");
CREATE INDEX IF NOT EXISTS "payment_status_idx" ON "payment" ("status");
CREATE INDEX IF NOT EXISTS "payment_approved_at_idx" ON "payment" ("approved_at");
CREATE INDEX IF NOT EXISTS "terms_policy_main_sub_idx" ON "terms_policy" ("main", "sub");
CREATE INDEX IF NOT EXISTS "privacy_policy_main_sub_idx" ON "privacy_policy" ("main", "sub");
CREATE INDEX IF NOT EXISTS "collected_post_user_id_idx" ON "collected_post" ("user_id");
CREATE INDEX IF NOT EXISTS "collected_post_channel_id_idx" ON "collected_post" ("channel_id");
CREATE INDEX IF NOT EXISTS "collected_post_deleted_at_idx" ON "collected_post" ("deleted_at");
CREATE INDEX IF NOT EXISTS "collected_post_created_at_idx" ON "collected_post" ("created_at");
CREATE INDEX IF NOT EXISTS "collected_post_external_id_idx" ON "collected_post" ("external_id");
CREATE INDEX IF NOT EXISTS "collected_post_image_collected_post_id_idx" ON "collected_post_image" ("collected_post_id");
CREATE INDEX IF NOT EXISTS "collected_post_image_sort_order_idx" ON "collected_post_image" ("sort_order");
CREATE INDEX IF NOT EXISTS "collected_post_image_file_hash_idx" ON "collected_post_image" ("file_hash");
CREATE INDEX IF NOT EXISTS "collected_post_comment_collected_post_id_idx" ON "collected_post_comment" ("collected_post_id");
CREATE INDEX IF NOT EXISTS "collected_post_comment_created_at_idx" ON "collected_post_comment" ("created_at");
CREATE INDEX IF NOT EXISTS "product_sales_daily_date_idx" ON "product_sales_daily" ("date");
CREATE INDEX IF NOT EXISTS "product_sales_daily_product_id_date_idx" ON "product_sales_daily" ("product_id", "date");
CREATE INDEX IF NOT EXISTS "product_user_id_idx" ON "product" ("user_id");
CREATE INDEX IF NOT EXISTS "product_channel_id_idx" ON "product" ("channel_id");
CREATE INDEX IF NOT EXISTS "product_collected_post_id_idx" ON "product" ("collected_post_id");
CREATE INDEX IF NOT EXISTS "product_category_id_idx" ON "product" ("category_id");
CREATE INDEX IF NOT EXISTS "product_created_at_idx" ON "product" ("created_at");
CREATE INDEX IF NOT EXISTS "product_deleted_at_idx" ON "product" ("deleted_at");
CREATE INDEX IF NOT EXISTS "product_variant_product_id_idx" ON "product_variant" ("product_id");
CREATE INDEX IF NOT EXISTS "product_variant_deleted_at_idx" ON "product_variant" ("deleted_at");
CREATE INDEX IF NOT EXISTS "product_option_product_id_idx" ON "product_option" ("product_id");
CREATE INDEX IF NOT EXISTS "product_option_group_name_idx" ON "product_option" ("group_name");
CREATE INDEX IF NOT EXISTS "product_image_product_id_idx" ON "product_image" ("product_id");
CREATE INDEX IF NOT EXISTS "product_image_file_hash_idx" ON "product_image" ("file_hash");
CREATE INDEX IF NOT EXISTS "refund_account_order_id_idx" ON "refund_account" ("order_id");
CREATE INDEX IF NOT EXISTS "refund_account_guest_order_id_idx" ON "refund_account" ("guest_order_id");
CREATE INDEX IF NOT EXISTS "return_request_user_id_idx" ON "return_request" ("user_id");
CREATE INDEX IF NOT EXISTS "return_request_order_id_idx" ON "return_request" ("order_id");
CREATE INDEX IF NOT EXISTS "return_request_status_idx" ON "return_request" ("status");
CREATE INDEX IF NOT EXISTS "return_request_user_id_status_idx" ON "return_request" ("user_id", "status");
CREATE INDEX IF NOT EXISTS "review_user_id_idx" ON "review" ("user_id");
CREATE INDEX IF NOT EXISTS "review_rating_idx" ON "review" ("rating");
CREATE INDEX IF NOT EXISTS "review_created_at_idx" ON "review" ("created_at");
CREATE INDEX IF NOT EXISTS "settlement_user_id_idx" ON "settlement" ("user_id");
CREATE INDEX IF NOT EXISTS "settlement_shop_id_idx" ON "settlement" ("shop_id");
CREATE INDEX IF NOT EXISTS "settlement_status_idx" ON "settlement" ("status");
CREATE INDEX IF NOT EXISTS "settlement_settled_at_idx" ON "settlement" ("settled_at");
CREATE INDEX IF NOT EXISTS "settlement_period_start_period_end_idx" ON "settlement" ("period_start", "period_end");
CREATE INDEX IF NOT EXISTS "settlement_user_id_shop_id_idx" ON "settlement" ("user_id", "shop_id");
CREATE INDEX IF NOT EXISTS "settlement_item_settlement_id_idx" ON "settlement_item" ("settlement_id");
CREATE INDEX IF NOT EXISTS "settlement_item_order_item_id_idx" ON "settlement_item" ("order_item_id");
CREATE INDEX IF NOT EXISTS "settlement_item_order_id_idx" ON "settlement_item" ("order_id");
CREATE INDEX IF NOT EXISTS "settlement_item_guest_order_item_id_idx" ON "settlement_item" ("guest_order_item_id");
CREATE INDEX IF NOT EXISTS "settlement_item_guest_order_id_idx" ON "settlement_item" ("guest_order_id");
CREATE INDEX IF NOT EXISTS "shipping_address_order_id_idx" ON "shipping_address" ("order_id");
CREATE INDEX IF NOT EXISTS "shipping_address_guest_order_id_idx" ON "shipping_address" ("guest_order_id");
CREATE INDEX IF NOT EXISTS "shop_product_user_id_idx" ON "shop_product" ("user_id");
CREATE INDEX IF NOT EXISTS "shop_product_product_id_idx" ON "shop_product" ("product_id");
CREATE INDEX IF NOT EXISTS "shop_product_shop_id_idx" ON "shop_product" ("shop_id");
CREATE INDEX IF NOT EXISTS "shop_product_deleted_at_idx" ON "shop_product" ("deleted_at");
CREATE INDEX IF NOT EXISTS "shop_user_id_idx" ON "shop" ("user_id");
CREATE INDEX IF NOT EXISTS "shop_subdomain_idx" ON "shop" ("subdomain");
CREATE INDEX IF NOT EXISTS "shop_is_active_idx" ON "shop" ("is_active");
CREATE INDEX IF NOT EXISTS "source_snapshot_product_id_checked_at_idx" ON "source_snapshot" ("product_id", "checked_at");
CREATE INDEX IF NOT EXISTS "price_history_product_id_created_at_idx" ON "price_history" ("product_id", "created_at");
CREATE INDEX IF NOT EXISTS "user_subscription_plan_id_idx" ON "user_subscription" ("plan_id");
CREATE INDEX IF NOT EXISTS "user_subscription_status_idx" ON "user_subscription" ("status");
CREATE INDEX IF NOT EXISTS "usage_log_date_idx" ON "usage_log" ("date");
CREATE INDEX IF NOT EXISTS "user_shop_id_idx" ON "user" ("shop_id");
CREATE INDEX IF NOT EXISTS "user_email_idx" ON "user" ("email");
CREATE INDEX IF NOT EXISTS "user_phone_idx" ON "user" ("phone");
CREATE INDEX IF NOT EXISTS "user_role_idx" ON "user" ("role");
CREATE INDEX IF NOT EXISTS "user_mode_idx" ON "user" ("mode");
CREATE INDEX IF NOT EXISTS "user_manager_id_idx" ON "user" ("manager_id");
CREATE INDEX IF NOT EXISTS "user_login_log_user_id_idx" ON "user_login_log" ("user_id");
CREATE INDEX IF NOT EXISTS "user_login_log_provider_idx" ON "user_login_log" ("provider");
CREATE INDEX IF NOT EXISTS "user_login_log_created_at_idx" ON "user_login_log" ("created_at");
CREATE INDEX IF NOT EXISTS "sourcing_api_config_user_id_idx" ON "sourcing_api_config" ("user_id");
CREATE INDEX IF NOT EXISTS "sourcing_api_config_platform_idx" ON "sourcing_api_config" ("platform");
CREATE INDEX IF NOT EXISTS "sourcing_api_config_is_active_idx" ON "sourcing_api_config" ("is_active");
CREATE INDEX IF NOT EXISTS "ai_api_config_user_id_idx" ON "ai_api_config" ("user_id");
CREATE INDEX IF NOT EXISTS "ai_api_config_provider_idx" ON "ai_api_config" ("provider");
CREATE INDEX IF NOT EXISTS "ai_api_config_is_active_idx" ON "ai_api_config" ("is_active");
CREATE INDEX IF NOT EXISTS "ai_prompt_config_user_id_idx" ON "ai_prompt_config" ("user_id");
CREATE INDEX IF NOT EXISTS "ai_prompt_config_prompt_type_idx" ON "ai_prompt_config" ("prompt_type");
CREATE INDEX IF NOT EXISTS "ai_prompt_config_is_active_idx" ON "ai_prompt_config" ("is_active");
CREATE INDEX IF NOT EXISTS "google_sheet_config_user_id_idx" ON "google_sheet_config" ("user_id");
CREATE INDEX IF NOT EXISTS "google_sheet_config_is_active_idx" ON "google_sheet_config" ("is_active");
CREATE INDEX IF NOT EXISTS "wholesale_band_catalog_is_active_idx" ON "wholesale_band_catalog" ("is_active");
CREATE INDEX IF NOT EXISTS "wholesale_band_catalog_deleted_at_idx" ON "wholesale_band_catalog" ("deleted_at");
CREATE INDEX IF NOT EXISTS "wishlist_user_id_idx" ON "wishlist" ("user_id");
CREATE INDEX IF NOT EXISTS "wishlist_product_id_idx" ON "wishlist" ("product_id");
CREATE INDEX IF NOT EXISTS "wishlist_user_id_added_at_idx" ON "wishlist" ("user_id", "added_at");